# Generated by Django 4.1 on 2023-10-02 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_api", "0002_followers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Followers",
            new_name="Follower",
        ),
        migrations.RenameModel(
            old_name="Post_details",
            new_name="Post_detail",
        ),
        migrations.RenameModel(
            old_name="User_details",
            new_name="User_detail",
        ),
    ]
